// Action types of the library
const actionTypes = {
  API_SET_ENDPOINT_HOST: "API_SET_ENDPOINT_HOST",
  API_SET_ENDPOINT_PATH: "API_SET_ENDPOINT_PATH",
  API_SET_HEADERS: "API_SET_HEADERS",
  API_SET_HEADER: "API_SET_HEADER",
  API_HYDRATE: "API_HYDRATE",
  API_WILL_CREATE: "API_WILL_CREATE",
  API_CREATED: "API_CREATED",
  API_CREATE_FAILED: "API_CREATE_FAILED",
  API_WILL_READ: "API_WILL_READ",
  API_READ: "API_READ",
  API_READ_FAILED: "API_READ_FAILED",
  API_WILL_UPDATE: "API_WILL_UPDATE",
  API_UPDATED: "API_UPDATED",
  API_UPDATE_FAILED: "API_UPDATE_FAILED",
  API_WILL_DELETE: "API_WILL_DELETE",
  API_DELETED: "API_DELETED",
  API_DELETE_FAILED: "API_DELETE_FAILED"
};

export default actionTypes;
